export const testlist = [
  {
    id: 1,
    title: "부적1",
    user: 1,
    content: "부적1내용입니다. 내용입니다.",
    image: "RABBIT",
    total_cheer: 5,
    cur_cheer: 4,
    is_created: false,
    created_at: "2023-01-13T10:34:01.382686+09:00",
    deleted_at: null,
    cheer: [
      {
        id: 1,
        charm: 1,
        nickname: "익명11(부적1)",
        content: "부적1의응원입니다1.",
      },
      {
        id: 2,
        charm: 1,
        nickname: "일이삼사오육칠팔구십일이",
        content: "부적1의응원입니다2.",
      },
      {
        id: 3,
        charm: 1,
        nickname: "익명3(부적1)",
        content: "부적1의응원입니다3.",
      },
      {
        id: 4,
        charm: 1,
        nickname: "익명4(부적1)",
        content: "부적1의응원입니다4.",
      },
    ],
  },
  {
    id: 2,
    title: "부적2이름",
    user: 1,
    content: "부적2내용입니다. 내용입니다.",
    image: "GOAT",
    total_cheer: 10,
    cur_cheer: 2,
    is_created: false,
    created_at: "2023-01-13T10:34:25.113108+09:00",
    deleted_at: null,
    cheer: [
      {
        id: 1,
        charm: 2,
        nickname: "부적2의응원1",
        content: "부적2의응원1입니다1.",
      },
      {
        id: 2,
        charm: 2,
        nickname: "부적2의응원2",
        content: "부적2의응원2입니다2.",
      },
    ],
  },
  {
    id: 3,
    title: "부적3이름",
    user: 1,
    content: "부적3의내용입니다. 내용입니다.",
    image: "SQUIRREL",
    total_cheer: 5,
    cur_cheer: 5,
    is_created: true,
    created_at: "2023-01-13T10:34:01.382686+09:00",
    deleted_at: null,
    cheer: [
      {
        id: 1,
        charm: 3,
        nickname: "일이삼사오육칠팔구십일이",
        content: "부적3의응원입니다1.",
      },
      {
        id: 2,
        charm: 3,
        nickname: "익명2(부적3)",
        content: "부적3의응원입니다2.",
      },
      {
        id: 3,
        charm: 3,
        nickname: "익명3(부적3)",
        content:
          "노랫말 또는 가사는 노래의 내용이 되는 글이나 말이다. 보통 가요, 가곡, 오페라 등의 말을 가리킨다. 가사가 없는 노래를 모음창이라고 한다. 악보에서는 음표의 아래에 가사를 넣는 것이 일반적이며, 간혹 위에 넣기도 한다. 노랫말 또는 가사는 노래의 내용이 되는 글이나 말이다. 보통 가요, 가곡, 오페라 등의 말을 가리킨다. 가사가 없는 노래를 모음창이라고 한다. 악보에서는 음표의 아래에 가사를 넣는 것이 일반적이며, 간혹 위에 넣기도 한다.",
      },
      {
        id: 4,
        charm: 3,
        nickname: "익명4(부적3",
        content: "부적3의응원입니다4.",
      },
      {
        id: 5,
        charm: 3,
        nickname: "익명5(부적3",
        content: "부적3의응원입니다5.",
      },
    ],
  },
];
