export const charmlist = [
  {
    id: 1,
    title: "hallo",
    user: 1,
    content: "hallo?",
    image: 1,
    total_cheer: 5,
    cur_cheer: 4,
    is_created: false,
    created_at: "2023-01-13T10:34:01.382686+09:00",
    deleted_at: null,
    cheer: [
      {
        id: 1,
        charm: 1,
        nickname: "hihi",
        content: "hihihihih",
      },
    ],
  },
  {
    id: 2,
    title: "Tschuss",
    user: 1,
    content: "Tschussi!",
    image: 2,
    total_cheer: 10,
    cur_cheer: 2,
    is_created: false,
    created_at: "2023-01-13T10:34:25.113108+09:00",
    deleted_at: null,
    cheer: [
      {
        id: 2,
        charm: 2,
        nickname: "dk",
        content: "dkdk",
      },
    ],
  },
  {
    id: 3,
    title: "부적3",
    user: 1,
    content: "부적3",
    image: 3,
    total_cheer: 20,
    cur_cheer: 10,
    is_created: true,
    created_at: "2023-01-13T10:34:01.382686+09:00",
    deleted_at: null,
    cheer: [
      {
        id: 1,
        charm: 1,
        nickname: "hihi",
        content: "hihihihih",
      },
    ],
  },
];
